name: graphql-flutter Code coverage

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: |
          cd packages/graphql_flutter
          flutter pub get
          flutter test --coverage
      - name: Upload coverage file
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov --file packages/graphql_flutter/coverage/lcov.info