name: graphql-flutter Dart Code sanity check

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.10.5'
      - run: make dep
      - run: make ci_fmt_flutter