name: graphql Code coverage

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - run: |
          cd packages/graphql
          pub get
          pub global activate coverage
          dart --enable_asserts --enable-vm-service test/coverage.dart
      - run: |
          cd packages/graphql
          bash <(curl -s https://codecov.io/bash) -F graphql_client
          bash <(curl -s https://codecov.io/bash) -F graphql_client -B `git rev-parse --abbrev-ref HEAD`_pseudo_branch_package_graphql_client
          dart analyze test