name: graphql-flutter Release Package

on:
  release:
    types: [created]
    tags:
      - graphql_flutter-v*
      - v*
  pull_request:
  workflow_run:
    workflows:
      - "graphql-flutter Dart Code sanity check"
      - "graphql-flutter Tests case"
    branches: [ main ]
    types:
      - completed

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2 # required!

      - name: 'publish graphql-flutter to to Pub.dev'
        uses: sakebook/actions-flutter-pub-publisher@v1.4.0
        with:
          credential: ${{ secrets.CREDENTIAL_JSON }}
          flutter_package: true
          skip_test: true
          dry_run: github.event_name != 'release'
          package_directory: './packages/graphql_flutter/'